### ISSUE TITLE
Getting top-k accuracy

### ISSUE THREAD

**Issue by jonhoo** [Lasagne/Lasagne#504]
Is there a straightforward way of having a Lasagne CNN (similar to the MNIST example) give me top-`k` accuracy instead of just exact match accuracy?

**Comment by f0k** [comment]
Please post usage questions on the mailing list: https://groups.google.com/forum/#!forum/lasagne-users
The github issue tracker is meant for bug reports and feature discussions. Thank you!

This being said, top-k accuracy shouldn't be too hard to come up with. Where top-1 accuracy is:
```python
accuracy = T.mean(T.eq(T.argmax(prediction, axis=1), target)), dtype=theano.config.floatX)
```
The top-k accuracy would be something like (untested):
```python
accuracy = T.mean(T.any(T.eq(T.argsort(prediction, axis=1)[:, -k:], target.dimshuffle('x', 0)), axis=1), dtype=theano.config.floatX)
```
I'll add this to `lasagne.objectives`.

**Comment by jonhoo** [comment]
@f0k You're right, I realized I should probably have posted this to the mailing list right after posting That said, this is a fairly common metric, so perhaps consider it a feature request?

**Comment by jonhoo** [comment]
Just FYI, to get this to run, I had to use
```python
accuracy = T.mean(T.any(T.eq(T.argsort(prediction, axis=1)[:, -k:], target.dimshuffle(0, 'x')), axis=0), dtype=theano.config.floatX)
```

**Comment by jonhoo** [comment]
Trying to use the code you give above, Theano complains about dimension mismatch. I'll start debugging, but my guess is there's a missing transpose somewhere?

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[1] = 5, input[1].shape[1] = 30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 135, in <module>
    err, acc1, acc5 = val_fn(batch[0], batch[1])
  File "/usr/lib/python3.5/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/lib/python3.5/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[1] = 5, input[1].shape[1] = 30)
Apply node that caused the error: Elemwise{eq,no_inplace}(Subtensor{::, int64::}.0, InplaceDimShuffle{x,0}.0)
Toposort index: 31
Inputs types: [TensorType(int64, matrix), TensorType(int32, row)]
Inputs shapes: [(30, 5), (1, 30)]
Inputs strides: [(80, 8), (120, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Any{1}(Elemwise{eq,no_inplace}.0)]]

Backtrace when the node is created:
  File "./main.py", line 91, in <module>
    test_5_acc = T.mean(T.any(T.eq(T.argsort(test_prediction, axis=1)[:, -5:], target_var.dimshuffle('x', 0)), axis=1), dtype=theano.config.floatX)
```

**Comment by jonhoo** [comment]
Ah, yes, seems like the arguments of the `dimshuffle` need to be reversed:
```python
accuracy = T.mean(T.any(T.eq(T.argsort(prediction, axis=1)[:, -k:], target.dimshuffle(0, 'x')), axis=1), dtype=theano.config.floatX)
```
