### ISSUE TITLE
Problem in Label Numbering in Binary CLassification

### ISSUE THREAD

**Issue by avisekiit** [Lasagne/Lasagne#616]
Hi All,

I am developing a CNN using Daniel's post. My task is binary (2 classes). So, in the output node I have assigned two nodes with softmax non-linearity.

**Snippet from my Network** (Please note the output section::)
```
`net=[
....
...
input_shape=(None, 3, image_size, image_size),
    conv1_num_filters=48, conv1_filter_size=(5, 5),
    conv21_num_filters=64, conv21_filter_size=(3, 3),  conv21_nonlinearity=lasagne.nonlinearities.rectify,
    conv22_num_filters=64, conv22_filter_size=(3, 3),  conv22_nonlinearity=lasagne.nonlinearities.rectify,
    pool1_pool_size=(2, 2), pool1_stride=1,

    conv31_num_filters=96, conv31_filter_size=(3, 3),  conv31_nonlinearity=lasagne.nonlinearities.rectify,
    conv32_num_filters=96, conv32_filter_size=(3, 3),  conv32_nonlinearity=lasagne.nonlinearities.rectify,

    dense1_num_units=256, dense1_nonlinearity=lasagne.nonlinearities.rectify,
    output_num_units=2, output_nonlinearity=lasagne.nonlinearities.softmax,

    update_learning_rate=theano.shared(float32(0.05)),
    update_momentum=theano.shared(float32(0.9)),

    on_epoch_finished=[
        AdjustVariable('update_learning_rate', start=0.05, stop=0.0001),
        AdjustVariable('update_momentum', start=0.9, stop=0.999),
        ],
    batch_iterator_train=BatchIterator(batch_size=64),
    max_epochs=1200,
    verbose=1,
    )
X=np.load('XG_try.npy')
y=np.load('yG_try.npy')
no_of_examples=X.shape[0]
y=y-1
z=y.reshape(no_of_examples,1)
print X.shape, z.shape, min(z.astype(int)), max(z.astype(int))
net.fit(X,z.astype(np.int32))
`
```
**Output of the program::**
```
`input                 (None, 3, 128, 128)     produces   49152 outputs
conv1                 (None, 48, 124, 124)    produces  738048 outputs
conv21                (None, 64, 122, 122)    produces  952576 outputs
conv22                (None, 64, 120, 120)    produces  921600 outputs
pool1                 (None, 64, 119, 119)    produces  906304 outputs
conv31                (None, 96, 117, 117)    produces 1314144 outputs
conv32                (None, 96, 115, 115)    produces 1269600 outputs
dense1                (None, 256)             produces     256 outputs
output                (None, 2)               produces       2 outputs
Traceback (most recent call last):
  File "try_train_v1_0.py", line 157, in <module>
    net.fit(X,z.astype(np.int32))
  File "/home/rs/asantra/anaconda2/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 293, in fit
    self.train_loop(X, y)
  File "/home/rs/asantra/anaconda2/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 300, in train_loop
    X, y, self.eval_size)
  File "/home/rs/asantra/anaconda2/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 401, in train_test_split
    kf = StratifiedKFold(y, round(1. / eval_size))
  File "/home/rs/asantra/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py", line 533, in __init__
    label_test_folds = test_folds[y == label]
IndexError: too many indices for array`
```

Any idea where I am getting wrong?
X.shape= (333853, 3, 24, 24)
z.shape=(333853, 1)
min(z)=0
max(z)=1

-Thanks,
Avisek

**Comment by f0k** [comment]
Closing because this belongs on the mailing list (and is already on the mailing list: https://groups.google.com/forum/#!topic/lasagne-users/oQyqs_89yPI).
