### ISSUE TITLE
MissingInputError

### ISSUE THREAD

**Issue by rafaelvalle** [Lasagne/Lasagne#654]
Hi all,

I'm getting a MissingInputError when running the code below. 
I'm not sure if it's from Theano, Lasagne or the way I'm instantiating the _update_fn_.
The error pops up when instantiating train_fn. It's pasted at the end.

```
nnet_params = {'n_layers': 4,
               'batch_size': 16,
               'epoch_size': 128,
               'widths': [None, 1024, 1024, 2],
               'non_linearities': (None,
                                   lasagne.nonlinearities.rectify,
                                   lasagne.nonlinearities.rectify,
                                   lasagne.nonlinearities.softmax),
               'update_func': lasagne.updates.adadelta,
               'drops': (None, 0.2, 0.5, None)}

hyperparameter_space = {
    'momentum': {'type': 'float', 'min': 0., 'max': 1.},
    'dropout': {'type': 'int', 'min': 0, 'max': 1},
    'learning_rate': {'type': 'float', 'min': .000001, 'max': .01},
    'network': {'type': 'enum', 'options': ['general_network']}
    }

layers = build_network_layers(
    (nnet_params['batch_size'], 112),
    nnet_params['n_layers'],
    nnet_params['widths'],
    nnet_params['non_linearities'],
    drop_out=hyperparameter_space['dropout'])

# Generate updates-creating function
updates_fn = functools.partial(
    nnet_params['update_func'],
    learning_rate=hyperparameter_space['learning_rate'],
    rho=hyperparameter_space['momentum'])

for epoch in train_function(data, layers, updates_function,
    nnet_params['batch_size'], nnet_params['epoch_size']):
    #...

def build_general_network(input_shape, n_layers, widths,
                          non_linearities, drop_out=True):
    # GlorotUniform is the default mechanism for initializing weights
    for i in range(n_layers):
        if i == 0:  # input layer
            layers = lasagne.layers.InputLayer(shape=input_shape)
        else:  # hidden and output layers
            layers = lasagne.layers.DenseLayer(layers,
                                               num_units=widths[i],
                                               nonlinearity=non_linearities[i])
            if drop_out and i < n_layers-1:  # output layer has no dropout
                layers = lasagne.layers.DropoutLayer(layers, p=0.5)
    return layers


def train(data, layers, updates_fn, batch_size=16, epoch_size=128,
          initial_patience=1000, improvement_threshold=0.99,
          patience_increase=5, max_iter=100000):

    # specify input and target theano data types
    input_var = T.fmatrix()
    target_var = T.ivector()

    # create a cost expression for training
    prediction = lasagne.layers.get_output(layers)
    cost = lasagne.objectives.categorical_crossentropy(
        prediction, target_var)
    cost = cost.mean()

    # create parameter update expressions for training
    params = lasagne.layers.get_all_params(layers, trainable=True)
    updates = updates_fn(cost, params)

    # compile functions for performing training step and returning
    # corresponding training cost
    train_fn = theano.function(inputs=[input_var, target_var],
                               outputs=cost,
                               updates=updates,
                               allow_input_downcast=True,
                               on_unused_input='warn')
    epoch_result = {}
    # ... ... ... #
    yield epoch_result
```
**Error**
```
/Users/rafaelvalle/Desktop/research/MDI/neural_networks.py:40: UserWarning: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 0 is not part of the computational graph needed to compute the outputs: input_var.
To make this warning into an error, you can pass the parameter on_unused_input='raise' to theano.function. To disable it completely, use on_unused_input='ignore'.
  on_unused_input='warn')
ERROR:
Traceback (most recent call last):
  File "/Users/rafaelvalle/Desktop/research/MDI/bayesian_parameter_optimization.py", line 84, in run_trial
    nnet_params['epoch_size']):
  File "/Users/rafaelvalle/Desktop/research/MDI/neural_networks.py", line 40, in train
    on_unused_input='warn')
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1428, in __init__
    accept_inplace)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 171, in __init__
    self.__import_r__(output, reason="init")
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 365, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 479, in __import__
    r)
MissingInputError: ("An input of the graph, used to compute dot(input, W), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", input)
```

**Comment by benanne** [comment]
The `input_var` you define is not linked in any way to the network.

Try replacing this line:
```prediction = lasagne.layers.get_output(layers)```

with:
```prediction = lasagne.layers.get_output(layers, input_var)```

Or another solution would be to pass the `input_var` when creating the `InputLayer`.

Please us the [mailing list](https://groups.google.com/forum/#!forum/lasagne-users) for support questions in the future, we'd prefer to keep the GitHub issue queue reserved for bugs and development. For more info take a look at the [contribution guidelines](https://github.com/Lasagne/Lasagne/blob/master/CONTRIBUTING.md) which are linked at the top of the issue submission form.

**Comment by rafaelvalle** [comment]
Thank you, Sander. I couldn't find the mailing list. Will post such doubts
there from now on.
Indeed, the problem was solved by replacing
prediction = lasagne.layers.get_output(layers)
with
prediction = lasagne.layers.get_output(layers, input_var)
