### ISSUE TITLE
Passing get_ouput() and vector as argument to theano

### ISSUE THREAD

**Issue by gadlimo** [Lasagne/Lasagne#657]
I'm having an odd error while trying to pass the output to train ( theano function)

```python
l_out = DenseLayer(l_hi, 2, nonlinearity = softmax)
output = get_output(l_out)
true_output = T.ivector('true_output')
(...)
args = [output, true_output]
train = theano.function(args, loss, updates = updates)
```

The error : 
```
Traceback (most recent call last):
  File "lasagne_test.py", line 35, in <module>
    train = theano.function(args, loss, updates = updates)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1465, in orig_function
    on_unused_input=on_unused_input).create(
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1133, in __init__
    fgraph, additional_outputs = std_fgraph(inputs, outputs, accept_inplace)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 141, in std_fgraph
    fgraph = gof.fg.FunctionGraph(orig_inputs, orig_outputs)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 135, in __init__
    self.__import_r__(outputs, reason="init")
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 257, in __import_r__
    self.__import__(apply_node, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 362, in __import__
    r)
theano.gof.fg.MissingInputError: ("An input of the graph, used to compute dot(input, W), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", input)
```

**Comment by benanne** [comment]
Your function arguments are wrong: `args = [output, true_output]`  should presumably be `args = [input_layer.input_var, true_output]`.

Please use the mailing list for questions like this, as indicated in our [contribution guidelines](https://github.com/Lasagne/Lasagne/blob/master/CONTRIBUTING.md). Thanks for your cooperation.
