### ISSUE TITLE
DenseLayer on top of a Pool2DLayer generates dimension mismatch error

### ISSUE THREAD

**Issue by Harhro94** [Lasagne/Lasagne#685]
Here is an example.

```
import random
import numpy as np

import lasagne
from theano import tensor as T
from lasagne import layers
from lasagne.nonlinearities import rectify

input_var = T.tensor4('input_var')
example = np.random.uniform(size=(1, 1, 6, 12), low=0.0, high=1.0).astype(np.float32)

network = layers.InputLayer(shape=(None, 1, 6, 12), input_var=input_var)
print "Input shape: ", layers.get_output(network).eval({input_var:example}).shape

pool_stride = 2 # works for 1 and 6. Crashes for 2, 3, 4, 5
print "Pooling stride: ", pool_stride

network = layers.MaxPool2DLayer(incoming=network, pool_size=(6, 6), stride=pool_stride, ignore_border=False)
print "Shape after pooling:", layers.get_output(network).eval({input_var:example}).shape

network = layers.DenseLayer(incoming=network, num_units=10, nonlinearity=rectify)
print "Shape after dense layer:", layers.get_output(network).eval({input_var:example}).shape

print "Success!"

```

This code generates the following.

```
Input shape:  (1, 1, 6, 12)
Pooling stride:  2
Shape after pooling: (1, 1, 2, 4)
Shape after dense layer:
Traceback (most recent call last):
  File "lasagne-pooling-bug.py", line 22, in <module>
    print "Shape after dense layer:", layers.get_output(network).eval({input_var:example}).shape
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 523, in eval
    rval = self._fn_cache[inputs](*args)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 908, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 895, in __call__
    self.fn() if output_subset is None else\
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 905, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.py", line 5438, in perform
    z[0] = numpy.asarray(numpy.dot(x, y))
ValueError: shapes (1,8) and (4,10) not aligned: 8 (dim 1) != 4 (dim 0)
Apply node that caused the error: dot(Reshape{2}.0, W)
Toposort index: 9
Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(1, 8), (4, 10)]
Inputs strides: [(32, 4), (40, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{add,no_inplace}(dot.0, DimShuffle{x,0}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "lasagne-pooling-bug.py", line 22, in <module>
    print "Shape after dense layer:", layers.get_output(network).eval({input_var:example}).shape
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/helper.py", line 191, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/dense.py", line 87, in get_output_for
    activation = T.dot(input, self.W)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

```

Seems this error comes when `ignore_border=False` and `pool_size` is equal to one of the dimensions of input.

Thank you.

**Comment by Hazarapet** [comment]
**+**

**Comment by skaae** [comment]
The problem is that report lasagne infers the output shape of the maxpooling layer to be

 `(None, 1, 1, 4)` but the actual shape is `(1, 1, 2, 4)`. I'm not really sure if this is a theano or a lasage bug? If the input_dim is 6 and the pooling size is 6 i would expect the output dim to be 1 (lasagne) not 2 (theano)?

**Comment by Harhro94** [comment]
if we write `network = layers.InputLayer(shape=(1, 1, 6, 12), input_var=input_var)` the error will still occur.
Somehow pooling layer says its output shape is `(1, 1, 1, 4)` but returns a 4D tensor of  shape `(1, 1, 2, 4) `.

**Comment by Harhro94** [comment]
Maybe I misunderstood something, but when `ignore_border=False` and `stride=2` I'd expect output dim to be `(1, 1, 3, 6)`.

**Comment by f0k** [comment]
Thanks for the report!

It's a Theano bug. Theano thinks the shape would be (1 1 1 4) as well:
```python
import theano
import theano.tensor as T
x = np.ones((6,12), dtype=theano.config.floatX)
y = T.signal.pool.pool_2d(T.constant(x), (6,6), False, (2,2))
print y.shape.eval()  # array([1, 4])
print y.eval().shape  # ERROR (theano.gof.opt): node: Reshape{2}(TensorConstant{(1, 1, 2, 4) of 1.0}, TensorConstant{[1 4]})
```

**Comment by Harhro94** [comment]
Now it's clear where the error comes from. 
Also I thought that when `ignore_border=False` then pooling will be done in all positions where pooling region intersects with the image in at least one point. So it is not correct. Only one partial pooling is done (of course if it is needed).

Thank you.

**Comment by f0k** [comment]
> Also I thought that when `ignore_border=False` then pooling will be done in all positions where pooling region intersects with the image in at least one point.

To achieve this, set `ignore_border=True` and pad with one less than the window size.
