### ISSUE TITLE
Non-unit value on shape on a broadcastable dimension

### ISSUE THREAD

**Issue by HornHehhf** [Lasagne/Lasagne#692]
I am desired to resolve this problem, please help!
Traceback (most recent call last):

  File "elman-forward.py", line 45, in <module>

    fnum0 = s['f0'], fnum1 = s['f1'], fnum2 = s['f2'], fnum3 = s['f3'], fnum4 = s['f4'], kalpha=s['kalpha'])

  File "C:\Users\nlp\charpos\fscore-1\blstm.py", line 305, in __init__

    updates = sentence_updates)

  File "C:\Anaconda\lib\site-packages\theano\compile\function.py", line 320, in function

    output_keys=output_keys)

  File "C:\Anaconda\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc

    output_keys=output_keys)

  File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", line 1777, in orig_function

    defaults)

  File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", line 1641, in create

    input_storage=input_storage_lists, storage_map=storage_map)

  File "C:\Anaconda\lib\site-packages\theano\gof\link.py", line 690, in make_thunk

    storage_map=storage_map)[:3]

  File "C:\Anaconda\lib\site-packages\theano\gof\vm.py", line 1003, in make_all

    no_recycling))

  File "C:\Anaconda\lib\site-packages\theano\scan_module\scan_op.py", line 856, in make_thunk

    on_unused_input='ignore')

  File "C:\Anaconda\lib\site-packages\theano\compile\function.py", line 320, in function

    output_keys=output_keys)

  File "C:\Anaconda\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc

    output_keys=output_keys)

  File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", line 1777, in orig_function

    defaults)

  File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", line 1657, in create

    self.return_none, self.output_keys, self)

  File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", line 417, in __init__

    c.value = value

  File "C:\Anaconda\lib\site-packages\theano\gof\link.py", line 468, in __set__

    self.storage[0] = self.type.filter(value, **kwargs)

  File "C:\Anaconda\lib\site-packages\theano\tensor\type.py", line 194, in filter

    " dimension.", data.shape, self.broadcastable)

TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn}(Elemwise{sub,no_inplace}.0, Elemwise{add,no_inplace}.0, Alloc.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{::int64}.0, Alloc.0, Alloc.0, Alloc.0, Elemwise{sub,no_inplace}.0, <TensorType(float64, matrix)>, Shape_i{1}.0, Shape_i{0}.0), '\n', 'Non-unit value on shape on a broadcastable dimension.', (0L, 0L), (False, True), 'Container name "None"')

**Comment by f0k** [comment]
Seems Theano thinks a particular dimension of a particular tensor should be broadcastable (have size 1), but it has a larger size. Make sure your input layer is defined using the exact same size you're passing later. If your input layer contains a `1` somewhere, try replacing it by a `None` to make that dimension flexible -- Theano seems to have a bug in `theano.scan` somewhere that gives odd results when some input dimensions are fixed to `1`.
If you cannot resolve the problem, please repost on our mailing list and include a minimal runnable code example to reproduce your problem. This issue tracker is meant to be reserved for bugs in Lasagne and feature discussions.

**Comment by HornHehhf** [comment]
@f0k ,Thank you very much! 
The bug is exactly what you say, and I have solved this problem.
Thank you!

**Comment by xiongxiaochu** [comment]
@HornHehhf would you please tell me how do you fix your problem?

**Comment by f0k** [comment]
> would you please tell me how do you fix your problem?

He solved it as I said above, by setting one of the input layer dimensions from `1` to `None`. But there are many different ways you could get this error. Can you post the last part of the stacktrace given with the error?
