### ISSUE TITLE
How to feed the varaint size of img to the lasagne net?

### ISSUE THREAD

**Issue by kingwenChen** [Lasagne/Lasagne#804]
```python
def SppNet(train_data, test_data,
		   input_layer=(None, 1, None, 6),
		   conv_layer=((3,3), 32),
		   spp_layer=([2,1], 'max'),
		   fc_layet=(256, 0.5),
		   output_layer=(10, ),
		   epochs=1, batch = 1):

	input = theano.tensor.tensor4('X')
	target = theano.tensor.ivector('Y')

	graph = lasagne.layers.InputLayer(input_layer, input)

	graph = lasagne.layers.Conv2DLayer(graph, conv_layer[1], conv_layer[0], nonlinearity=lasagne.nonlinearities.leaky_rectify)

	# graph = lasagne.layers.Pool2DLayer(graph, (3, 3), stride=2, mode='max')
	# graph = lasagne.layers.MaxPool2DLayer(graph, pool_size=(2, 2))

	graph = lasagne.layers.SpatialPyramidPoolingDNNLayer(graph, spp_layer[0], spp_layer[1])

	graph = lasagne.layers.DenseLayer(
		lasagne.layers.dropout(graph, p=.5),
		num_units=256,
		nonlinearity=lasagne.nonlinearities.rectify)

	graph = lasagne.layers.DenseLayer(
		lasagne.layers.dropout(graph, p=.5),
		num_units=10,
		nonlinearity=lasagne.nonlinearities.softmax)

	output = lasagne.layers.get_output(graph)
	loss = lasagne.objectives.categorical_crossentropy(output, target).mean()

	params = lasagne.layers.get_all_params(graph, trainable=True)
	updates = lasagne.updates.nesterov_momentum(loss, params, learning_rate=0.1, momentum=0.9)

	print('build graph finish')
	print('build train')
	train = theano.function([input, target], loss, updates=updates)
	print('start epoch')
	# train network (assuming you've got some training data in numpy arrays)
	
	for epoch in range(epochs):
		loss = 0
		for input_batch, target_batch, length_batch in train_data.epoch(batch):
			loss += train(input_batch, target_batch)
		print("Epoch %d: Loss %g" % (epoch + 1, loss / len(train_data)))

	# use trained network for predictions
	
	test = lasagne.layers.get_output(graph, deterministic=True)
	predict = theano.function([input], theano.tensor.argmax(test, axis=1))
	# accracy = theano.function([])
	print("Predicted class for first test input: %r" % predict(test_data[0]))
	# print("Predicted accary for first test input: %r" % len(theano.tensor.argmax(predict(test_data[0])) = theano.tensor.argmax(test_data[1]))/len(test_data[0)
```
mini input sample:
```
input_batch = [
array([[[1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])
 array([[[0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 0, 0, 0],
        [1, 0, 1, 0, 1],
        [0, 1, 1, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1]]])
]

target_batch=[array([0, 1, 0, 0, 0, 1]) array([1, 0, 0, 0, 1, 0])]

Traceback (most recent call last):
  File "TheanoNet.py", line 84, in <module>
    TheanoNet.SppNet(train, test)
  File "TheanoNet.py", line 59, in SppNet
    loss += train(input_batch, target_batch)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 786, in __call__
    allow_downcast=s.allow_downcast)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 149, in filter
    converted_data = theano._asarray(data, self.dtype)
  File "/usr/local/lib/python2.7/dist-packages/theano/misc/safe_asarray.py", line 33, in _asarray
    rval = numpy.asarray(a, dtype=dtype, order=order)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: ('Bad input argument to theano function with name "TheanoNet.py:52"  at index 0(0-based)', 'setting an array element with a sequence.')
```
The error point out can't put variant shape to tensor4.
any one know how to handle this problem?

**Comment by f0k** [comment]
> The error point out can't put variant shape to tensor4.

By definition, a tensor has a fixed size in each dimension. So you cannot combine images of different sizes in a single mini-batch. You will either need to group images of the same size into separate mini-batches (e.g., have a mini-batch with only 48x48 images, and another one with only 52x45 images), or employ some kind of masking (e.g., remember which part of the mini-batch tensor contains valid input and make sure only that part participates in the loss function -- this is easy with global pooling in the end, but hard with spatial pyramid pooling as you'll end up having to pool each image on its own).

In the future, please post such usage questions to the mailing list; the issue tracker is meant for bugs and feature discussions only (i.e., anything that requires a change in Lasagne's codebase). Thank you!
