### ISSUE TITLE
Compilation failing when running recurrent example

### ISSUE THREAD

**Issue by anishpdoshi** [Lasagne/Lasagne#807]
I am trying to run the example at https://github.com/Lasagne/Lasagne/blob/master/examples/recurrent.py, but it has continuously been failing with the following output:

(I'm running lasagne 0.2.dev1 and theano 0.9.0rc2, which were installed using the bleeding-edge installation process. In another issue I saw that deleting ~/.theano sometimes worked, but it did not work in my case).

anything i'm doing wrong?

Problem occurred during compilation with the command line below:
```
/usr/bin/clang++ -dynamiclib -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=corei7-avx -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/lib/python2.7/site-packages/theano/gof -L/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib -fvisibility=hidden -o /Users/apdoshi/.theano/compiledir_Darwin-16.1.0-x86_64-i386-64bit-i386-2.7.9-64/tmpxJtoVQ/3c45156e54b3d452c74e9594265b10e3.so /Users/apdoshi/.theano/compiledir_Darwin-16.1.0-x86_64-i386-64bit-i386-2.7.9-64/tmpxJtoVQ/mod.cpp
/Users/apdoshi/.theano/compiledir_Darwin-16.1.0-x86_64-i386-64bit-i386-2.7.9-64/tmpxJtoVQ/mod.cpp:676:21: warning: comparison of array 'outputs' equal to a null pointer is always false [-Wtautological-pointer-compare]
                if (outputs == NULL) {
                    ^~~~~~~    ~~~~
/Users/apdoshi/.theano/compiledir_Darwin-16.1.0-x86_64-i386-64bit-i386-2.7.9-64/tmpxJtoVQ/mod.cpp:701:54: error: arithmetic on a pointer to void
                                    PyArray_DATA(V3) + data_offset,
                                    ~~~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.

Traceback (most recent call last):
  File "recurrent.py", line 171, in <module>
    main()
  File "recurrent.py", line 152, in main
    cost, updates=updates)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python2.7/site-packages/theano/gof/vm.py", line 1063, in make_all
    impl=impl))
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2304, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Split{2}(CGer{destructive}.0, TensorConstant{1}, MakeVector{dtype='int64'}.0), '\n', "Compilation failed (return status=1): /Users/apdoshi/.theano/compiledir_Darwin-16.1.0-x86_64-i386-64bit-i386-2.7.9-64/tmpxJtoVQ/mod.cpp:676:21: warning: comparison of array 'outputs' equal to a null pointer is always false [-Wtautological-pointer-compare].                 if (outputs == NULL) {.                     ^~~~~~~    ~~~~. /Users/apdoshi/.theano/compiledir_Darwin-16.1.0-x86_64-i386-64bit-i386-2.7.9-64/tmpxJtoVQ/mod.cpp:701:54: error: arithmetic on a pointer to void.                                     PyArray_DATA(V3) + data_offset,.                                     ~~~~~~~~~~~~~~~~ ^. 1 warning and 1 error generated.. ", '[*1 -> Split{2}(<TensorType(float64, matrix)>, TensorConstant{1}, <TensorType(int64, vector)>), *1::1]')
```

**Comment by f0k** [comment]
> anything i'm doing wrong?

I don't think so. This might be a Theano bug. On my machine, the example runs fine, but I'm on Ubuntu with gcc, not on Mac with clang. Just to be sure this hasn't been fixed already, are you running the very latest Theano version from `pip install https://github.com/Theano/Theano/archive/master.zip` or is it already a few days old?

**Comment by anishpdoshi** [comment]
Thanks for the response @f0k . You're right, turns out this was a theano bug, since I got the sam error with Keras as well. 
I was able to fix it by installing theano== '0.9.0b1' instead of the 0.9.0rc2 that i had gotten from the bleeding edge repo. The strange thing is now Theano compilation on my CPU is immensely slow :(

Since this issue is fixed and not related to Lasagne, I'll close it now.

**Comment by nouiz** [comment]
Which version of clang and xcode do you use? I think that version could be
more strict.

**Comment by nouiz** [comment]
We have a PR in Theano to fix this. Should be merged tonight or tomorrow.

The slow down could be due to recompiling c code. So it should be done only
once. Otherwise it was due to not having recent optimisation that was
included.
