### ISSUE TITLE
DisconnectedInputError while computing updates of a cost function that uses subtensors

### ISSUE THREAD

**Issue by BeNikis** [Lasagne/Lasagne#833]
I'm trying to build a simple modification of a vanilla autoencoder with a cost function from the Information Theoretic Learning camp,and for that I need to take each pixel of both the input and output batches as a seperate variable but I keep getting this error:
```
Traceback (most recent call last):
  File "autoencoder.py", line 442, in <module>
    main()
  File "autoencoder.py", line 409, in main
    net=autoencoder(net,25,100,X_train,5)
  File "autoencoder.py", line 261, in autoencoder
    updates=lasagne.updates.adam(cost,main_parameters)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/updates.py", line 583, in adam
    all_grads = get_or_compute_grads(loss_or_grads, params)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/updates.py", line 123, in get_or_compute_grads
    return theano.grad(loss_or_grads, params)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 539, in grad
    handle_disconnected(elem)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 526, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError:  
Backtrace when that variable is created:

  File "autoencoder.py", line 442, in <module>
    main()
  File "autoencoder.py", line 409, in main
    net=autoencoder(net,25,100,X_train,5)
  File "autoencoder.py", line 222, in autoencoder
    decoder=lasagne.layers.DenseLayer(main_net,reduce(lambda x,y:x*y,data.shape[1:]))
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/dense.py", line 71, in __init__
    self.W = self.add_param(W, (num_inputs, num_units), name="W")
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/base.py", line 234, in add_param
    param = utils.create_param(spec, shape, name)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/utils.py", line 355, in create_param
    spec = theano.shared(spec, broadcastable=bcast)
```

The relevant code is:

```
def autoencoder(input_net,batch_size,hid_units,data,epochs):
    
    
    input_var=T.dtensor4()#T.TensorType('float32',(False,)*len(lasagne.layers.get_output_shape(lasagne.layers.get_all_layers(input_net)[0])))
    input_net_out=lasagne.layers.get_output(input_net,input_var)
    
    layers_added=len(lasagne.layers.get_all_layers(input_net))
    
    main_net=lasagne.layers.DenseLayer(input_net,hid_units)#,nonlinearity=lasagne.nonlinearities.sigmoid)
    main_net=lasagne.layers.batch_norm(main_net)
    
    decoder=lasagne.layers.DenseLayer(main_net,reduce(lambda x,y:x*y,data.shape[1:]))
    decoder=lasagne.layers.batch_norm(decoder)
    decoder_outp=lasagne.layers.get_output(decoder,input_var).reshape((-1,)+data.shape[1:])
    
    main_parameters=[]
    layers_added-=len(lasagne.layers.get_all_layers(main_net))   
    
    for i in range(layers_added,0):
        print(i)
        main_parameters+=lasagne.layers.get_all_layers(decoder)[i].get_params(trainable=True)        
    
    for i in range(layers_added,0):
        print(i)
        main_parameters+=lasagne.layers.get_all_layers(main_net)[i].get_params(trainable=True)
 
    
    print(len(main_parameters))
    
    print("cost_function")
    
    input_matrices=[]
    sub_shape,subs=gen_subs(input_var,data.shape,batch_size,(1,1,1))
    print(sub_shape)
    for sub in subs:
        input_matrices.append(pairwise_ker(sub,0.01,batch_size))
    
    output_matrices=[]
    sub_shape,subs=gen_subs(decoder_outp,data.shape,batch_size,(1,1,1))
    for sub in subs:
        output_matrices.append(pairwise_ker(sub,0.01,batch_size))    
    
    cost=T.constant(0)
    entropy=matrix_entropy_op() 
    
    for x,y in zip(input_matrices,output_matrices):
        cost-=entropy(x)+entropy(y)-entropy(x*y)
    
    #cost=lasagne.objectives.squared_error(input_var,decoder_outp).mean()
    
    updates=lasagne.updates.adam(cost,main_parameters)



def gen_subs(var,shape,batchsize,spacings):
    
    dims = len(shape)-1
    dim_slices = []
    for i in range(dims):
        dim_slices.append([])
        
    for i,dim in enumerate(dim_slices):
        starts=range(0,shape[i+1],spacings[i])
        
        
        for start in range(len(starts)-1):
            dim.append(slice(starts[start],starts[start+1]))
        dim.append(slice(starts[-1],shape[i+1]+1))
        
    subs=itertools.product([slice(0,batchsize+1)],*dim_slices)
    print(len(list(subs)))
    return tuple((batchsize,)+spacings),map(lambda x:var[x],subs)
```

I had trouble with subtensors in the past,but now I seem to be stuck.Excuse me if I missed something simple.

The full code is [here](https://gist.github.com/BeNikis/5470a1f8255245d628c909a67c36afc3)

**Comment by f0k** [comment]
The code looks a bit messy (e.g., `input_net_out` is never used), I don't have the time to fully read it -- but there must be some parameters in your `main_parameters` array that do not participate in your `cost` expression. It even tells you one of the parameters: The weight matrix of the dense layer created in line 222 of `autoencoder.py`.

In future, please post usage problems on our mailing list (https://groups.google.com/forum/#!forum/lasagne-users), the issue tracker is meant for bug reports and feature discussions only (i.e., things that require a change of the Lasagne code base rather than the user code).
