### ISSUE TITLE
ImportError: cannot import name downsample

### ISSUE THREAD

**Issue by loretoparisi** [Lasagne/Lasagne#867]
Using:

```
(.env) [loretoparisi@:mbploreto SIF]$ python -c "import theano; print theano .__version__"
0.9.0
```

```
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import lasagne
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
entailment
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import lasagne
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
sentiment
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import lasagne
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/Users/loretoparisi/Documents/MyProjects/SIF/.env/lib/python2.7/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
```

At this time I have fixed in this way

So I have solved in this way:

```
(.env) [loretoparisi@:mbploreto SIF]$ pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
Collecting https://github.com/Lasagne/Lasagne/archive/master.zip
  Downloading https://github.com/Lasagne/Lasagne/archive/master.zip
     | 235kB 905kB/s
Requirement already up-to-date: numpy in ./.env/lib/python2.7/site-packages (from Lasagne==0.2.dev1)
Installing collected packages: Lasagne
  Found existing installation: Lasagne 0.1
    Uninstalling Lasagne-0.1:
      Successfully uninstalled Lasagne-0.1
  Running setup.py install for Lasagne ... done
Successfully installed Lasagne-0.2.dev1
(.env) [loretoparisi@:mbploreto SIF]$ python -c "import lasagne; print lasagne .__version__"
0.2.dev1
```

**Comment by f0k** [comment]
Lasagne 0.1 is only guaranteed to work with the Theano version mentioned in its `requirements.txt`, as described at: http://lasagne.readthedocs.io/en/latest/user/installation.html#stable-lasagne-release
For the most recent Theano, you will need bleeding-edge Lasagne from github, as you noticed yourself.
