### ISSUE TITLE
Doubt with weights in Lasagne.Objective.Aggregate

### ISSUE THREAD

**Issue by ffalfred** [Lasagne/Lasagne#876]
Hello,

I am trying to weight the loss function, but instead of using a constant previously set up like: 

class_weights = theano.constant(np.array([0.5, 1, 1, 0.2, 1], dtype=theano.config.floatX))  # weight first class by 0.5, fourth class by 0.2, all others fully by 1.0
loss = lasagne.objectives.categorical_crossentropy(predictions, targets)
loss = lasagne.objectives.aggregate(loss, weights=class_weights[targets])

I would like to use a number that comes with each sample (like a mask). It could be similar to:
    btrainx,btrainy,btrainm,btrainiden = preparedata.batchcreation_ext(trainx,trainy,trainm,trainiden,size_batch,shuffle=True)
    target_values = T.tensor3('target_output')
    mask_var = T.matrix('mask')
    input_var = T.tensor3('inputs')
    identity_values = T.vector('identity')
    network=.....
    network_output = lasagne.layers.get_output(network,deterministic=False)
    predicted_values = np.squeeze(network_output)
    cost_iden = T.mean((predicted_values-target_values)**2)
    cost_iden_agg = lasagne.objectives.aggregate(cost_iden,weights=identity_values,mode='mean')
    all_params = lasagne.layers.get_all_params(network,trainable=True)
    updates = lasagne.updates.adam(cost_iden_agg, all_params, learning_rate)
    train = theano.function(inputs=[input_var, target_values,mask_var,identity_values],outputs=cost_iden_agg, updates=updates)
    for i in range(len(btrainx)):
        print(i,len(btrainx))
        mask=np.squeeze(btrainm[i])
        train(btrainx[i], btrainy[i], mask,btrainiden[i].reshape((size_batch)))

But everytime I try this last one, an error appears:

Traceback (most recent call last):
  File "main_ext_train.py", line 205, in <module>
    net,results_arr=train(trainx_fold1,trainy_fold1,trainm_fold1,trainiden_fold1,valx_fold1,valy_fold1,valm_fold1,[0.001,2,10,6,0.6,0.5,10,10,10,10,10])
  File "main_ext_train.py", line 155, in train
    compute_cost = theano.function(inputs=[input_var, target_values, mask_var],outputs=[dcost,dpredicted_values],updates=updates)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 1794, in orig_function
    output_keys=output_keys).create(
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 1446, in __init__
    accept_inplace)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/fg.py", line 180, in __init__
    self.__import_r__(output, reason="init")
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/fg.py", line 351, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/fg.py", line 397, in __import__
    raise MissingInputError(error_msg, variable=r)
theano.gof.fg.MissingInputError: Input 1 of the graph (indices start from 0), used to compute Elemwise{mul,no_inplace}(TensorConstant{[ 0.5     ...30000001]}, identity), was not provided and not given a value. Use the Theano flag exception_verbosity='high', for more information on this error.
Backtrace when that variable is created:

  File "main_ext_train.py", line 205, in <module>
    net,results_arr=train(trainx_fold1,trainy_fold1,trainm_fold1,trainiden_fold1,valx_fold1,valy_fold1,valm_fold1,[0.001,2,10,6,0.6,0.5,10,10,10,10,10])
  File "main_ext_train.py", line 136, in train
    identity_values = T.vector('identity')

Backtrace when the variable is created:
  File "main_ext_train.py", line 205, in <module>
    net,results_arr=train(trainx_fold1,trainy_fold1,trainm_fold1,trainiden_fold1,valx_fold1,valy_fold1,valm_fold1,[0.001,2,10,6,0.6,0.5,10,10,10,10,10])
  File "main_ext_train.py", line 136, in train
    identity_values = T.vector('identity')

 
I hope someone can help... :)

**Comment by ffalfred** [comment]
I found out my mistake, it was refered to the cost function, not the train
