### ISSUE TITLE
'TensorVariable' object has no attribute 'output_shape'

### ISSUE THREAD

**Issue by saitarslanboun** [Lasagne/Lasagne#888]
Hi,

I have the following lines;

```
vector_j = theano.tensor.reshape(self.masked_v, ((self.batch_size, -1)))
fc1 = lasagne.layers.DenseLayer(vector_j, num_units=512)
```

vector_j is a theano tensor variable with shape (128, 16), and masked_v is a tensor variable with shape (128, 1, 16, 1). When I try to feed it into fc1, I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    main(vars(args))
  File "main.py", line 8, in main
    model = CapsNet(args)
  File "/gpfs/hpchome/hasan90/capsules/CapsNet-Theano/capsNet.py", line 23, in __init__
    self.build_arch()
  File "/gpfs/hpchome/hasan90/capsules/CapsNet-Theano/capsNet.py", line 74, in build_arch
    fc1 = lasagne.layers.DenseLayer(vector_j, num_units=512)
  File "/gpfs/hpchome/hasan90/build/anaconda2/lib/python2.7/site-packages/lasagne/layers/dense.py", line 78, in __init__
    super(DenseLayer, self).__init__(incoming, **kwargs)
  File "/gpfs/hpchome/hasan90/build/anaconda2/lib/python2.7/site-packages/lasagne/layers/base.py", line 37, in __init__
    self.input_shape = incoming.output_shape
AttributeError: 'TensorVariable' object has no attribute 'output_shape'
```

What is the reason, and how I can solve the problem?

**Comment by f0k** [comment]
A Lasagne layer cannot directly take a Theano expression as its input, because that doesn't allow shape inference. You'll need to wrap it in an `InputLayer`:
```python
vector_j = theano.tensor.reshape(self.masked_v, ((self.batch_size, -1)))
inp = lasagne.layers.InputLayer(vector_j, (self.batch_size, X))  # you will need to specify X here
fc1 = lasagne.layers.DenseLayer(inp, num_units=512)
```
